export const products = [
    {
        title: "Daler Rowney Georgian 200ml",
        price: 10.50,
        image: "https://yzels.lt/wp-content/uploads/2020/06/sonet-8x10-ml-473x473.jpg",
        slur: "1",
        description: "Aliejiniai dažai skiedžiami vandeniu Georgian, tai alternatyva tradiciniams aliejiniams dažams. Dažus  galima maišyti, skiesti ir plauti vandeniu. Nėra specifinio kvapo. Dažai išdžiūsta per 5 - 7 dienas.",
        cartQuantity: 0,
        category: 'dazai',
        rating: 1000,
    },
    {
        title: "Gruntuotas kartonas 10x10 cm",
        price: 0.65,
        image: "https://popieriausbankas.lt/wp-content/uploads/2019/11/CKB-kartonas-1030x1030.jpg",
        slur: "2",
        description: "Iš rudo perdirbto popieriaus pagamintas, ekologiškas gofruotas kartonas. Puikiai tinka Jūsų produkcijos pakavimui bei sandėliavimui. Apsaugo stiklinius, metalinius, medinius gaminius nuo įbrėžimų ar fizinių pažeidimų. Plačiai naudojamas baldų pramonėje. Kartonas išsilanksto į bet kokią formą, yra atsparus smūgiams.",
        cartQuantity: 0,
        category: 'popierius',
        rating: 980,
    },
    {
      title: "Spalvotas popierius 10x10cm",
      price: 0.29,
      image: "https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/6996_6401.jpg",
      slur: "3",
      description: "Spalvotas biuro popierius",
      cartQuantity: 0,
      category: 'popierius',
      rating: 197,
    },
    {
      title: "Molbertas-platus",
      price: 69.99,
      image: "https://vunder.ee/media/extra_6630.jpg",
      slur: "4",
      description: "aukštis 2,00 m,plotis 38-66cm,lentyneles 60 cm, viršutinęs laikykles ir apatinę lentynas galima sureguliuoti,pagal paveikslo išmatavimus. Pagamintas iš pušys,nedažytas",
      category: 'molbertai',
      cartQuantity: 0,
      rating: 128,
    },
    {
      title: "Piešimo drobė Artico, 40x50 cm",
      price: 6.99,
      image: "https://m.media-amazon.com/images/I/61WNJGJuqVL.jpg",
      slur: "5",
      description: "Tinka piešti visų tipų dažais.",
      category: 'drobes',
      cartQuantity: 0,
      rating: 168,
    },
  ]