export const products = [
    {
        title: "Daler Rowney Georgian 200ml",
        price: 10.50,
        image: "https://yzels.lt/wp-content/uploads/2020/06/sonet-8x10-ml-473x473.jpg",
        slur: "1",
        description: "Aliejiniai dažai skiedžiami vandeniu Georgian, tai alternatyva tradiciniams aliejiniams dažams. Dažus  galima maišyti, skiesti ir plauti vandeniu. Nėra specifinio kvapo. Dažai išdžiūsta per 5 - 7 dienas.",
        cartQuantity: 0,
        category: 'dazai',
    },
    {
        title: "Gruntuotas kartonas 10x10 cm",
        price: 0.65,
        image: "https://popieriausbankas.lt/wp-content/uploads/2019/11/CKB-kartonas-1030x1030.jpg",
        slur: "2",
        description: "Iš rudo perdirbto popieriaus pagamintas, ekologiškas gofruotas kartonas. Puikiai tinka Jūsų produkcijos pakavimui bei sandėliavimui. Apsaugo stiklinius, metalinius, medinius gaminius nuo įbrėžimų ar fizinių pažeidimų. Plačiai naudojamas baldų pramonėje. Kartonas išsilanksto į bet kokią formą, yra atsparus smūgiams.",
        cartQuantity: 0,
        category: 'popierius',
    },
    {
      title: "Spalvotas popierius 10x10cm",
      price: 29.99,
      image: "https://www.officewarehouse.com.ph/__resources/_web_data_/products/products/image_gallery/6996_6401.jpg",
      slur: "3",
      description: "Spalvotas biuro popierius",
      cartQuantity: 0,
      category: 'popierius',
    },
    {
      title: "shit",
      price: 29.99,
      image: "img",
      slur: "4",
      description: "sagfasgsagsagsagasgsagsagsag",
      category: 'molbertai',
      cartQuantity: 0,
    },
    {
      title: "shit",
      price: 29.99,
      image: "img",
      slur: "5",
      description: "veryboutiful",
      category: 'drobes',
      cartQuantity: 0,
    },
  ]